### ISSUE TITLE
Create a Writer file for `.gr` and `.co` files

### ISSUE THREAD

**Issue by shawnBGU** [dorinma/GraphGeneratorTool#1]
[click here](http://www.diag.uniroma1.it//challenge9/download.shtml) for example of how the files look like.

For the `.gr` files:

- [x] Comment lines start with `c`
- [x] Description of the graph start with `p`
- [x] Edges lines (Arcs) start with `a`
   Example of an `a`rc  line: `a 1 2 3` - an arc from vertex `1` to vertex `2` with cost `3`

For the `.co` files:

- [x] Comment lines start with `c`
- [x] Description of the graph start with `p`
- [x] Vertices lines start with `v`
   Example of a `v`ertex  line: `v 1 2 3 4` - vertex `1` with x coordinate `2`, y coordinate `3`, and z coordinate `4`

**Comment by bshahar** [comment]
-
