### ISSUE TITLE
Giving Weights to Edges

### ISSUE THREAD

**Issue by shawnBGU** [dorinma/GraphGeneratorTool#5]
Every edge has `n` weights, It should be different in each edges file.

Suggested methods
- [x]  Fully Random
- [x]  For Planar or grid graphs - computed value
- [x] Some other calculation - e.g., if the index is less than `x` then the cost is `rand(y,z)` else `rand(abs(2y-z), 3z+y)`
- [x] etc

**Comment by bshahar** [comment]
.
